//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 09:23:40 PM CET 
//


package rs.ac.uns.ftn.tim5.apiorganvlasti.model.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Razlog.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Razlog">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="није поступио"/>
 *     &lt;enumeration value="није поступио у целости"/>
 *     &lt;enumeration value="у законском року"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Razlog")
@XmlEnum
public enum Razlog {

    @XmlEnumValue("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e")
    НИЈЕ_ПОСТУПИО("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e"),
    @XmlEnumValue("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438")
    НИЈЕ_ПОСТУПИО_У_ЦЕЛОСТИ("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438"),
    @XmlEnumValue("\u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443")
    У_ЗАКОНСКОМ_РОКУ("\u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443");
    private final String value;

    Razlog(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Razlog fromValue(String v) {
        for (Razlog c: Razlog.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
