version: "3.7"
services:
  emailservice:
    build:
      context: .
      dockerfile: .docker.java/Dockerfile
    ports:
      - "8088:8080"
    environment:
      EMAIL_SENDER: 45714aa73b-598c81@inbox.mailtrap.io
    networks:
      - email-service-netowrk

networks:
  email-service-netowrk:
    name: email-service-netowrk
