//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.26 at 05:21:23 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.izvestaj;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statistika_zahteva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broj_prihvacenih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="broj_odbijenih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="broj_isteklih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statistika_zalbi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broj_zalbi_na_odluku" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="zalbe_cutanja">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nije_postupio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="nije_postupio_u_celosti" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
 *         &lt;element name="datum_podnosenja">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://ftn.uns.ac.rs.tim5/model/predicate" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statistikaZahteva",
    "statistikaZalbi",
    "organVlasti",
    "datumPodnosenja"
})
@XmlRootElement(name = "Izvestaj")
public class Izvestaj implements Identifiable {

    @XmlElement(name = "statistika_zahteva", required = true)
    protected StatistikaZahteva statistikaZahteva;
    @XmlElement(name = "statistika_zalbi", required = true)
    protected StatistikaZalbi statistikaZalbi;
    @XmlElement(name = "organ_vlasti", required = true)
    protected TPravnoLice organVlasti;
    @XmlElement(name = "datum_podnosenja", required = true)
    protected DatumPodnosenja datumPodnosenja;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anyURI")
    protected String about;
    @XmlAttribute(name = "vocab")
    protected String vocab;

    /**
     * Gets the value of the statistikaZahteva property.
     *
     * @return
     *     possible object is
     *     {@link StatistikaZahteva }
     *
     */
    public StatistikaZahteva getStatistikaZahteva() {
        return statistikaZahteva;
    }

    /**
     * Sets the value of the statistikaZahteva property.
     *
     * @param value
     *     allowed object is
     *     {@link StatistikaZahteva }
     *
     */
    public void setStatistikaZahteva(StatistikaZahteva value) {
        this.statistikaZahteva = value;
    }

    /**
     * Gets the value of the statistikaZalbi property.
     *
     * @return
     *     possible object is
     *     {@link StatistikaZalbi }
     *
     */
    public StatistikaZalbi getStatistikaZalbi() {
        return statistikaZalbi;
    }

    /**
     * Sets the value of the statistikaZalbi property.
     *
     * @param value
     *     allowed object is
     *     {@link StatistikaZalbi }
     *
     */
    public void setStatistikaZalbi(StatistikaZalbi value) {
        this.statistikaZalbi = value;
    }

    /**
     * Gets the value of the organVlasti property.
     *
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *
     */
    public TPravnoLice getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     *
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *
     */
    public void setOrganVlasti(TPravnoLice value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     *
     * @return
     *     possible object is
     *     {@link DatumPodnosenja }
     *
     */
    public DatumPodnosenja getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     *
     * @param value
     *     allowed object is
     *     {@link DatumPodnosenja }
     *
     */
    public void setDatumPodnosenja(DatumPodnosenja value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the vocab property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVocab() {
        if (vocab == null) {
            return "http://ftn.uns.ac.rs.tim5/model/predicate";
        } else {
            return vocab;
        }
    }

    /**
     * Sets the value of the vocab property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVocab(String value) {
        this.vocab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DatumPodnosenja
        extends Datum
    {

        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the property property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getProperty() {
            if (property == null) {
                return "pred:datum";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broj_prihvacenih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="broj_odbijenih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="broj_isteklih" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPrihvacenih",
        "brojOdbijenih",
        "brojIsteklih"
    })
    public static class StatistikaZahteva {

        @XmlElement(name = "broj_prihvacenih", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger brojPrihvacenih;
        @XmlElement(name = "broj_odbijenih", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger brojOdbijenih;
        @XmlElement(name = "broj_isteklih", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger brojIsteklih;

        /**
         * Gets the value of the brojPrihvacenih property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getBrojPrihvacenih() {
            return brojPrihvacenih;
        }

        /**
         * Sets the value of the brojPrihvacenih property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setBrojPrihvacenih(BigInteger value) {
            this.brojPrihvacenih = value;
        }

        /**
         * Gets the value of the brojOdbijenih property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getBrojOdbijenih() {
            return brojOdbijenih;
        }

        /**
         * Sets the value of the brojOdbijenih property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setBrojOdbijenih(BigInteger value) {
            this.brojOdbijenih = value;
        }

        /**
         * Gets the value of the brojIsteklih property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getBrojIsteklih() {
            return brojIsteklih;
        }

        /**
         * Sets the value of the brojIsteklih property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setBrojIsteklih(BigInteger value) {
            this.brojIsteklih = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broj_zalbi_na_odluku" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="zalbe_cutanja">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nije_postupio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="nije_postupio_u_celosti" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojZalbiNaOdluku",
        "zalbeCutanja"
    })
    public static class StatistikaZalbi {

        @XmlElement(name = "broj_zalbi_na_odluku", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger brojZalbiNaOdluku;
        @XmlElement(name = "zalbe_cutanja", required = true)
        protected ZalbeCutanja zalbeCutanja;

        /**
         * Gets the value of the brojZalbiNaOdluku property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getBrojZalbiNaOdluku() {
            return brojZalbiNaOdluku;
        }

        /**
         * Sets the value of the brojZalbiNaOdluku property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setBrojZalbiNaOdluku(BigInteger value) {
            this.brojZalbiNaOdluku = value;
        }

        /**
         * Gets the value of the zalbeCutanja property.
         *
         * @return
         *     possible object is
         *     {@link ZalbeCutanja }
         *
         */
        public ZalbeCutanja getZalbeCutanja() {
            return zalbeCutanja;
        }

        /**
         * Sets the value of the zalbeCutanja property.
         *
         * @param value
         *     allowed object is
         *     {@link ZalbeCutanja }
         *
         */
        public void setZalbeCutanja(ZalbeCutanja value) {
            this.zalbeCutanja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nije_postupio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="nije_postupio_u_celosti" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nijePostupio",
            "nijePostupioUCelosti"
        })
        public static class ZalbeCutanja {

            @XmlElement(name = "nije_postupio", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger nijePostupio;
            @XmlElement(name = "nije_postupio_u_celosti", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger nijePostupioUCelosti;

            /**
             * Gets the value of the nijePostupio property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNijePostupio() {
                return nijePostupio;
            }

            /**
             * Sets the value of the nijePostupio property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNijePostupio(BigInteger value) {
                this.nijePostupio = value;
            }

            /**
             * Gets the value of the nijePostupioUCelosti property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNijePostupioUCelosti() {
                return nijePostupioUCelosti;
            }

            /**
             * Sets the value of the nijePostupioUCelosti property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNijePostupioUCelosti(BigInteger value) {
                this.nijePostupioUCelosti = value;
            }

        }

    }

}
