//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.26 at 05:21:23 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.izvestaj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.izvestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.izvestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Izvestaj.StatistikaZalbi }
     * 
     */
    public Izvestaj.StatistikaZalbi createIzvestajStatistikaZalbi() {
        return new Izvestaj.StatistikaZalbi();
    }

    /**
     * Create an instance of {@link KolekcijaIzvestaja }
     * 
     */
    public KolekcijaIzvestaja createKolekcijaIzvestaja() {
        return new KolekcijaIzvestaja();
    }

    /**
     * Create an instance of {@link Izvestaj.StatistikaZahteva }
     * 
     */
    public Izvestaj.StatistikaZahteva createIzvestajStatistikaZahteva() {
        return new Izvestaj.StatistikaZahteva();
    }

    /**
     * Create an instance of {@link Izvestaj.DatumPodnosenja }
     * 
     */
    public Izvestaj.DatumPodnosenja createIzvestajDatumPodnosenja() {
        return new Izvestaj.DatumPodnosenja();
    }

    /**
     * Create an instance of {@link Izvestaj.StatistikaZalbi.ZalbeCutanja }
     * 
     */
    public Izvestaj.StatistikaZalbi.ZalbeCutanja createIzvestajStatistikaZalbiZalbeCutanja() {
        return new Izvestaj.StatistikaZalbi.ZalbeCutanja();
    }

}
