//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:20:32 PM CET 
//


package model.obavestenje;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Trazilac" type="{http://ftn.uns.ac.rs/tim5/util}TFizicko_Lice"/&gt;
 *         &lt;element name="Organ" type="{http://ftn.uns.ac.rs/tim5/util}TPravno_Lice"/&gt;
 *         &lt;element name="Predmet"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Broj_Predmeta" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="Datum" type="{http://ftn.uns.ac.rs/tim5/util}Datum"/&gt;
 *                   &lt;element name="Opis_Trazene_Informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Pravni_Osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="Odgovor" type="{http://ftn.uns.ac.rs/tim5/util}TOdgovor_Na_Zahtev" maxOccurs="unbounded"/&gt;
 *                   &lt;element name="Uplata" type="{http://ftn.uns.ac.rs/tim5/util}TUplata" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trazilac",
    "organ",
    "predmet"
})
@XmlRootElement(name = "Obavestenje", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje")
public class Obavestenje {

    @XmlElement(name = "Trazilac", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
    protected TFizickoLice trazilac;
    @XmlElement(name = "Organ", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
    protected TPravnoLice organ;
    @XmlElement(name = "Predmet", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
    protected Obavestenje.Predmet predmet;

    /**
     * Gets the value of the trazilac property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getTrazilac() {
        return trazilac;
    }

    /**
     * Sets the value of the trazilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setTrazilac(TFizickoLice value) {
        this.trazilac = value;
    }

    /**
     * Gets the value of the organ property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrgan(TPravnoLice value) {
        this.organ = value;
    }

    /**
     * Gets the value of the predmet property.
     * 
     * @return
     *     possible object is
     *     {@link Obavestenje.Predmet }
     *     
     */
    public Obavestenje.Predmet getPredmet() {
        return predmet;
    }

    /**
     * Sets the value of the predmet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obavestenje.Predmet }
     *     
     */
    public void setPredmet(Obavestenje.Predmet value) {
        this.predmet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Broj_Predmeta" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="Datum" type="{http://ftn.uns.ac.rs/tim5/util}Datum"/&gt;
     *         &lt;element name="Opis_Trazene_Informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Pravni_Osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Odgovor" type="{http://ftn.uns.ac.rs/tim5/util}TOdgovor_Na_Zahtev" maxOccurs="unbounded"/&gt;
     *         &lt;element name="Uplata" type="{http://ftn.uns.ac.rs/tim5/util}TUplata" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPredmeta",
        "datum",
        "opisTrazeneInformacije",
        "pravniOsnov",
        "odgovor",
        "uplata"
    })
    public static class Predmet {

        @XmlElement(name = "Broj_Predmeta", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje")
        protected int brojPredmeta;
        @XmlElement(name = "Datum", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
        protected Datum datum;
        @XmlElement(name = "Opis_Trazene_Informacije", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
        protected String opisTrazeneInformacije;
        @XmlElement(name = "Pravni_Osnov", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje")
        protected List<TPravniOsnov> pravniOsnov;
        @XmlElement(name = "Odgovor", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje", required = true)
        protected List<TOdgovorNaZahtev> odgovor;
        @XmlElement(name = "Uplata", namespace = "http://ftn.uns.ac.rs/tim5/obavestenje")
        protected TUplata uplata;

        /**
         * Gets the value of the brojPredmeta property.
         * 
         */
        public int getBrojPredmeta() {
            return brojPredmeta;
        }

        /**
         * Sets the value of the brojPredmeta property.
         * 
         */
        public void setBrojPredmeta(int value) {
            this.brojPredmeta = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link Datum }
         *     
         */
        public Datum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Datum }
         *     
         */
        public void setDatum(Datum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the opisTrazeneInformacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisTrazeneInformacije() {
            return opisTrazeneInformacije;
        }

        /**
         * Sets the value of the opisTrazeneInformacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisTrazeneInformacije(String value) {
            this.opisTrazeneInformacije = value;
        }

        /**
         * Gets the value of the pravniOsnov property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the pravniOsnov property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPravniOsnov().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPravniOsnov }
         * 
         * 
         */
        public List<TPravniOsnov> getPravniOsnov() {
            if (pravniOsnov == null) {
                pravniOsnov = new ArrayList<TPravniOsnov>();
            }
            return this.pravniOsnov;
        }

        /**
         * Gets the value of the odgovor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the odgovor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOdgovor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TOdgovorNaZahtev }
         * 
         * 
         */
        public List<TOdgovorNaZahtev> getOdgovor() {
            if (odgovor == null) {
                odgovor = new ArrayList<TOdgovorNaZahtev>();
            }
            return this.odgovor;
        }

        /**
         * Gets the value of the uplata property.
         * 
         * @return
         *     possible object is
         *     {@link TUplata }
         *     
         */
        public TUplata getUplata() {
            return uplata;
        }

        /**
         * Sets the value of the uplata property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUplata }
         *     
         */
        public void setUplata(TUplata value) {
            this.uplata = value;
        }

    }

}
