//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:20:32 PM CET 
//


package model.obavestenje;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TUplata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TUplata"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Racun" type="{http://ftn.uns.ac.rs/tim5/util}TRacun"/&gt;
 *         &lt;element name="Iznos" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Poziv_Na_Broj" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="Pravni_Osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TUplata", propOrder = {
    "racun",
    "iznos",
    "pozivNaBroj",
    "pravniOsnov"
})
public class TUplata {

    @XmlElement(name = "Racun", required = true)
    protected TRacun racun;
    @XmlElement(name = "Iznos", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger iznos;
    @XmlElement(name = "Poziv_Na_Broj", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pozivNaBroj;
    @XmlElement(name = "Pravni_Osnov")
    protected TPravniOsnov pravniOsnov;

    /**
     * Gets the value of the racun property.
     * 
     * @return
     *     possible object is
     *     {@link TRacun }
     *     
     */
    public TRacun getRacun() {
        return racun;
    }

    /**
     * Sets the value of the racun property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRacun }
     *     
     */
    public void setRacun(TRacun value) {
        this.racun = value;
    }

    /**
     * Gets the value of the iznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIznos() {
        return iznos;
    }

    /**
     * Sets the value of the iznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIznos(BigInteger value) {
        this.iznos = value;
    }

    /**
     * Gets the value of the pozivNaBroj property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPozivNaBroj() {
        return pozivNaBroj;
    }

    /**
     * Sets the value of the pozivNaBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPozivNaBroj(BigInteger value) {
        this.pozivNaBroj = value;
    }

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link TPravniOsnov }
     *     
     */
    public TPravniOsnov getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravniOsnov }
     *     
     */
    public void setPravniOsnov(TPravniOsnov value) {
        this.pravniOsnov = value;
    }

}
