//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 03:09:41 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link KolekcijaZahteva }
     * 
     */
    public KolekcijaZahteva createKolekcijaZahteva() {
        return new KolekcijaZahteva();
    }

    /**
     * Create an instance of {@link Zahtev.Trazilac }
     * 
     */
    public Zahtev.Trazilac createZahtevTrazilac() {
        return new Zahtev.Trazilac();
    }

    /**
     * Create an instance of {@link Zahtev.Organ }
     * 
     */
    public Zahtev.Organ createZahtevOrgan() {
        return new Zahtev.Organ();
    }

    /**
     * Create an instance of {@link Zahtev.ElementiZahteva }
     * 
     */
    public Zahtev.ElementiZahteva createZahtevElementiZahteva() {
        return new Zahtev.ElementiZahteva();
    }

    /**
     * Create an instance of {@link Zahtev.Datum }
     * 
     */
    public Zahtev.Datum createZahtevDatum() {
        return new Zahtev.Datum();
    }

    /**
     * Create an instance of {@link Zahtev.Mesto }
     * 
     */
    public Zahtev.Mesto createZahtevMesto() {
        return new Zahtev.Mesto();
    }

}
