//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.04 at 09:48:55 AM CET 
//


package rs.ac.uns.ftn.tim5.model.zahtev;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TElementZahteva;
import rs.ac.uns.ftn.tim5.model.util.TFizickoLice;
import rs.ac.uns.ftn.tim5.model.util.TPravniOsnov;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trazilac" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
 *         &lt;element name="organ" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
 *         &lt;element name="pravni_osnov" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravni_Osnov" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="opis_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="elementi_zahteva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Element_Zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}TElement_Zahteva" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datum" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_gradjanina" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trazilac",
    "organ",
    "pravniOsnov",
    "opisZahteva",
    "elementiZahteva",
    "datum",
    "mesto"
})
@XmlRootElement(name = "Zahtev")
public class Zahtev implements Identifiable {

    @XmlElement(required = true)
    protected TFizickoLice trazilac;
    @XmlElement(required = true)
    protected TPravnoLice organ;
    @XmlElement(name = "pravni_osnov")
    protected List<TPravniOsnov> pravniOsnov;
    @XmlElement(name = "opis_zahteva", required = true)
    protected String opisZahteva;
    @XmlElement(name = "elementi_zahteva", required = true)
    protected Zahtev.ElementiZahteva elementiZahteva;
    @XmlElement(required = true)
    protected Datum datum;
    @XmlElement(required = true)
    protected String mesto;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "id_gradjanina")
    protected Long idGradjanina;

    /**
     * Gets the value of the trazilac property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getTrazilac() {
        return trazilac;
    }

    /**
     * Sets the value of the trazilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setTrazilac(TFizickoLice value) {
        this.trazilac = value;
    }

    /**
     * Gets the value of the organ property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrgan(TPravnoLice value) {
        this.organ = value;
    }

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pravniOsnov property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPravniOsnov().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPravniOsnov }
     * 
     * 
     */
    public List<TPravniOsnov> getPravniOsnov() {
        if (pravniOsnov == null) {
            pravniOsnov = new ArrayList<TPravniOsnov>();
        }
        return this.pravniOsnov;
    }

    /**
     * Gets the value of the opisZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisZahteva() {
        return opisZahteva;
    }

    /**
     * Sets the value of the opisZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisZahteva(String value) {
        this.opisZahteva = value;
    }

    /**
     * Gets the value of the elementiZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link Zahtev.ElementiZahteva }
     *     
     */
    public Zahtev.ElementiZahteva getElementiZahteva() {
        return elementiZahteva;
    }

    /**
     * Sets the value of the elementiZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zahtev.ElementiZahteva }
     *     
     */
    public void setElementiZahteva(Zahtev.ElementiZahteva value) {
        this.elementiZahteva = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatum(Datum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idGradjanina property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdGradjanina() {
        return idGradjanina;
    }

    /**
     * Sets the value of the idGradjanina property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdGradjanina(Long value) {
        this.idGradjanina = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Element_Zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}TElement_Zahteva" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementZahteva"
    })
    public static class ElementiZahteva {

        @XmlElement(name = "Element_Zahteva", required = true)
        protected List<TElementZahteva> elementZahteva;

        /**
         * Gets the value of the elementZahteva property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementZahteva property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementZahteva().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TElementZahteva }
         * 
         * 
         */
        public List<TElementZahteva> getElementZahteva() {
            if (elementZahteva == null) {
                elementZahteva = new ArrayList<TElementZahteva>();
            }
            return this.elementZahteva;
        }

    }

}
