//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.04 at 07:43:17 PM CET 
//


package rs.ac.uns.ftn.tim5.model.zalba_cutanja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TFizickoLice;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poverenik" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
 *         &lt;element name="zalilac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="osnovni_podaci" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
 *                   &lt;element name="drugi_podaci_za_kontakt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
 *         &lt;element name="razlog_zalbe">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="nije postupio"/>
 *               &lt;enumeration value="nije postupio u celosti"/>
 *               &lt;enumeration value="nije postupio u zakonskom roku"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *         &lt;element name="zahtevana_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mesto_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum_zalbe" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_zahteva" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_poverenika" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poverenik",
    "zalilac",
    "organVlasti",
    "razlogZalbe",
    "datumZahteva",
    "zahtevanaInformacije",
    "mestoZalbe",
    "datumZalbe"
})
@XmlRootElement(name = "Zalba_cutanja")
public class ZalbaCutanja implements Identifiable {

    @XmlElement(required = true)
    protected TFizickoLice poverenik;
    @XmlElement(required = true)
    protected ZalbaCutanja.Zalilac zalilac;
    @XmlElement(name = "organ_vlasti", required = true)
    protected TPravnoLice organVlasti;
    @XmlElement(name = "razlog_zalbe", required = true)
    protected String razlogZalbe;
    @XmlElement(name = "datum_zahteva", required = true)
    protected Datum datumZahteva;
    @XmlElement(name = "zahtevana_informacije", required = true)
    protected String zahtevanaInformacije;
    @XmlElement(name = "mesto_zalbe", required = true)
    protected String mestoZalbe;
    @XmlElement(name = "datum_zalbe", required = true)
    protected Datum datumZalbe;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "id_zahteva")
    protected Long idZahteva;
    @XmlAttribute(name = "id_poverenika")
    protected Long idPoverenika;

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPoverenik(TFizickoLice value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the zalilac property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaCutanja.Zalilac }
     *     
     */
    public ZalbaCutanja.Zalilac getZalilac() {
        return zalilac;
    }

    /**
     * Sets the value of the zalilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaCutanja.Zalilac }
     *     
     */
    public void setZalilac(ZalbaCutanja.Zalilac value) {
        this.zalilac = value;
    }

    /**
     * Gets the value of the organVlasti property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrganVlasti(TPravnoLice value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the razlogZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlogZalbe() {
        return razlogZalbe;
    }

    /**
     * Sets the value of the razlogZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlogZalbe(String value) {
        this.razlogZalbe = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatumZahteva(Datum value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the zahtevanaInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevanaInformacije() {
        return zahtevanaInformacije;
    }

    /**
     * Sets the value of the zahtevanaInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevanaInformacije(String value) {
        this.zahtevanaInformacije = value;
    }

    /**
     * Gets the value of the mestoZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMestoZalbe() {
        return mestoZalbe;
    }

    /**
     * Sets the value of the mestoZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMestoZalbe(String value) {
        this.mestoZalbe = value;
    }

    /**
     * Gets the value of the datumZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatumZalbe() {
        return datumZalbe;
    }

    /**
     * Sets the value of the datumZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatumZalbe(Datum value) {
        this.datumZalbe = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdZahteva() {
        return idZahteva;
    }

    /**
     * Sets the value of the idZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdZahteva(Long value) {
        this.idZahteva = value;
    }

    /**
     * Gets the value of the idPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdPoverenika() {
        return idPoverenika;
    }

    /**
     * Sets the value of the idPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdPoverenika(Long value) {
        this.idPoverenika = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="osnovni_podaci" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
     *         &lt;element name="drugi_podaci_za_kontakt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovniPodaci",
        "drugiPodaciZaKontakt"
    })
    public static class Zalilac {

        @XmlElement(name = "osnovni_podaci", required = true)
        protected TFizickoLice osnovniPodaci;
        @XmlElement(name = "drugi_podaci_za_kontakt")
        protected String drugiPodaciZaKontakt;

        /**
         * Gets the value of the osnovniPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getOsnovniPodaci() {
            return osnovniPodaci;
        }

        /**
         * Sets the value of the osnovniPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setOsnovniPodaci(TFizickoLice value) {
            this.osnovniPodaci = value;
        }

        /**
         * Gets the value of the drugiPodaciZaKontakt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrugiPodaciZaKontakt() {
            return drugiPodaciZaKontakt;
        }

        /**
         * Sets the value of the drugiPodaciZaKontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrugiPodaciZaKontakt(String value) {
            this.drugiPodaciZaKontakt = value;
        }

    }

}
