//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:34:08 PM CET 
//


package model.zalbaNaOdluku;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Razlog.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="Razlog"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e"/&gt;
 *     &lt;enumeration value="\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438"/&gt;
 *     &lt;enumeration value="\u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Razlog")
@XmlEnum
public enum Razlog {

    @XmlEnumValue("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e")
    \u041d\u0418\u0408\u0415_\u041f\u041e\u0421\u0422\u0423\u041f\u0418\u041e("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e"),
    @XmlEnumValue("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438")
    \u041d\u0418\u0408\u0415_\u041f\u041e\u0421\u0422\u0423\u041f\u0418\u041e_\u0423_\u0426\u0415\u041b\u041e\u0421\u0422\u0418("\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e \u0443 \u0446\u0435\u043b\u043e\u0441\u0442\u0438"),
    @XmlEnumValue("\u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443")
    \u0423_\u0417\u0410\u041a\u041e\u041d\u0421\u041a\u041e\u041c_\u0420\u041e\u041a\u0423("\u0443 \u0437\u0430\u043a\u043e\u043d\u0441\u043a\u043e\u043c \u0440\u043e\u043a\u0443");
    private final String value;

    Razlog(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Razlog fromValue(String v) {
        for (Razlog c: Razlog.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
