//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:32:19 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/tim5/util", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.util;
