//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 03:23:35 PM CET 
//


package rs.ac.uns.ftn.tim5.apipoverenik.model.zalba_na_odluku;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.apipoverenik.model.zalba_na_odluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.apipoverenik.model.zalba_na_odluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Poverenik }
     * 
     */
    public ZalbaNaOdluku.Poverenik createZalbaNaOdlukuPoverenik() {
        return new ZalbaNaOdluku.Poverenik();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Odluka }
     * 
     */
    public ZalbaNaOdluku.Odluka createZalbaNaOdlukuOdluka() {
        return new ZalbaNaOdluku.Odluka();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Zakon }
     * 
     */
    public ZalbaNaOdluku.Zakon createZalbaNaOdlukuZakon() {
        return new ZalbaNaOdluku.Zakon();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.PodnosilacZalbe }
     * 
     */
    public ZalbaNaOdluku.PodnosilacZalbe createZalbaNaOdlukuPodnosilacZalbe() {
        return new ZalbaNaOdluku.PodnosilacZalbe();
    }

}
