//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 01:40:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://ftn.uns.ac.rs/tim5/apipoverenik/model/zalba_na_odluku",
        xmlns = {
                @XmlNs(namespaceURI = "http://ftn.uns.ac.rs/tim5/apipoverenik/model/util", prefix = "ns2"),
                @XmlNs(namespaceURI = "http://ftn.uns.ac.rs/tim5/apipoverenik/model/zalba_na_odluku", prefix = "")
        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.tim5.apipoverenik.model.zalba_na_odluku;

import javax.xml.bind.annotation.XmlNs;