//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 01:40:34 PM CET 
//


package rs.ac.uns.ftn.tim5.apipoverenik.model.zalba_na_odluku;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import rs.ac.uns.ftn.tim5.apipoverenik.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.apipoverenik.model.util.Adresa;
import rs.ac.uns.ftn.tim5.apipoverenik.model.util.Datum;
import rs.ac.uns.ftn.tim5.apipoverenik.model.util.TFizickoLice;
import rs.ac.uns.ftn.tim5.apipoverenik.model.util.TPravniOsnov;
import rs.ac.uns.ftn.tim5.apipoverenik.model.util.TPravnoLice;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Poverenik">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Adresa" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}Adresa"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Zalilac" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}TFizicko_Lice"/>
 *         &lt;element name="organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}TPravno_Lice"/>
 *         &lt;element name="odluka">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broj_odluke">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="godina">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Datum" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}Datum"/>
 *         &lt;element name="Osnova_za_zaljenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Zakon" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}TPravni_Osnov"/>
 *         &lt;element name="Mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datum_zahteva" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}Datum"/>
 *         &lt;element name="Podnosilac_zalbe">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Obavezni_podaci" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}TFizicko_Lice"/>
 *                   &lt;element name="Kontakt_podaci" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "poverenik",
        "zalilac",
        "organVlasti",
        "odluka",
        "datum",
        "osnovaZaZaljenje",
        "zakon",
        "mesto",
        "datumZahteva",
        "podnosilacZalbe"
})
@XmlRootElement(name = "Zalba_na_odluku")
public class ZalbaNaOdluku implements Identifiable {

    protected Long id;
    @XmlElement(name = "Poverenik", required = true)
    protected ZalbaNaOdluku.Poverenik poverenik;
    @XmlElement(name = "Zalilac", required = true)
    protected TFizickoLice zalilac;
    @XmlElement(name = "organ_vlasti", required = true)
    protected TPravnoLice organVlasti;
    @XmlElement(required = true)
    protected ZalbaNaOdluku.Odluka odluka;
    @XmlElement(name = "Datum", required = true)
    protected Datum datum;
    @XmlElement(name = "Osnova_za_zaljenje", required = true)
    protected String osnovaZaZaljenje;
    @XmlElement(name = "Zakon", required = true)
    protected TPravniOsnov zakon;
    @XmlElement(name = "Mesto", required = true)
    protected String mesto;
    @XmlElement(name = "Datum_zahteva", required = true)
    protected Datum datumZahteva;
    @XmlElement(name = "Podnosilac_zalbe", required = true)
    protected ZalbaNaOdluku.PodnosilacZalbe podnosilacZalbe;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the poverenik property.
     *
     * @return possible object is
     * {@link ZalbaNaOdluku.Poverenik }
     */
    public ZalbaNaOdluku.Poverenik getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     *
     * @param value allowed object is
     *              {@link ZalbaNaOdluku.Poverenik }
     */
    public void setPoverenik(ZalbaNaOdluku.Poverenik value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the zalilac property.
     *
     * @return possible object is
     * {@link TFizickoLice }
     */
    public TFizickoLice getZalilac() {
        return zalilac;
    }

    /**
     * Sets the value of the zalilac property.
     *
     * @param value allowed object is
     *              {@link TFizickoLice }
     */
    public void setZalilac(TFizickoLice value) {
        this.zalilac = value;
    }

    /**
     * Gets the value of the organVlasti property.
     *
     * @return possible object is
     * {@link TPravnoLice }
     */
    public TPravnoLice getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     *
     * @param value allowed object is
     *              {@link TPravnoLice }
     */
    public void setOrganVlasti(TPravnoLice value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the odluka property.
     *
     * @return possible object is
     * {@link ZalbaNaOdluku.Odluka }
     */
    public ZalbaNaOdluku.Odluka getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     *
     * @param value allowed object is
     *              {@link ZalbaNaOdluku.Odluka }
     */
    public void setOdluka(ZalbaNaOdluku.Odluka value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return possible object is
     * {@link Datum }
     */
    public Datum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value allowed object is
     *              {@link Datum }
     */
    public void setDatum(Datum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the osnovaZaZaljenje property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOsnovaZaZaljenje() {
        return osnovaZaZaljenje;
    }

    /**
     * Sets the value of the osnovaZaZaljenje property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOsnovaZaZaljenje(String value) {
        this.osnovaZaZaljenje = value;
    }

    /**
     * Gets the value of the zakon property.
     *
     * @return possible object is
     * {@link TPravniOsnov }
     */
    public TPravniOsnov getZakon() {
        return zakon;
    }

    /**
     * Sets the value of the zakon property.
     *
     * @param value allowed object is
     *              {@link TPravniOsnov }
     */
    public void setZakon(TPravniOsnov value) {
        this.zakon = value;
    }

    /**
     * Gets the value of the mesto property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     *
     * @return possible object is
     * {@link Datum }
     */
    public Datum getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     *
     * @param value allowed object is
     *              {@link Datum }
     */
    public void setDatumZahteva(Datum value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the podnosilacZalbe property.
     *
     * @return possible object is
     * {@link ZalbaNaOdluku.PodnosilacZalbe }
     */
    public ZalbaNaOdluku.PodnosilacZalbe getPodnosilacZalbe() {
        return podnosilacZalbe;
    }

    /**
     * Sets the value of the podnosilacZalbe property.
     *
     * @param value allowed object is
     *              {@link ZalbaNaOdluku.PodnosilacZalbe }
     */
    public void setPodnosilacZalbe(ZalbaNaOdluku.PodnosilacZalbe value) {
        this.podnosilacZalbe = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broj_odluke">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="godina">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "brojOdluke",
            "godina"
    })
    public static class Odluka {

        @XmlElement(name = "broj_odluke", required = true, defaultValue = "1")
        protected BigInteger brojOdluke;
        @XmlElement(required = true, defaultValue = "2020")
        protected XMLGregorianCalendar godina;

        /**
         * Gets the value of the brojOdluke property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getBrojOdluke() {
            return brojOdluke;
        }

        /**
         * Sets the value of the brojOdluke property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setBrojOdluke(BigInteger value) {
            this.brojOdluke = value;
        }

        /**
         * Gets the value of the godina property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getGodina() {
            return godina;
        }

        /**
         * Sets the value of the godina property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setGodina(XMLGregorianCalendar value) {
            this.godina = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Obavezni_podaci" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}TFizicko_Lice"/>
     *         &lt;element name="Kontakt_podaci" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "obavezniPodaci",
            "kontaktPodaci"
    })
    public static class PodnosilacZalbe {

        @XmlElement(name = "Obavezni_podaci", required = true)
        protected TFizickoLice obavezniPodaci;
        @XmlElement(name = "Kontakt_podaci")
        protected String kontaktPodaci;

        /**
         * Gets the value of the obavezniPodaci property.
         *
         * @return possible object is
         * {@link TFizickoLice }
         */
        public TFizickoLice getObavezniPodaci() {
            return obavezniPodaci;
        }

        /**
         * Sets the value of the obavezniPodaci property.
         *
         * @param value allowed object is
         *              {@link TFizickoLice }
         */
        public void setObavezniPodaci(TFizickoLice value) {
            this.obavezniPodaci = value;
        }

        /**
         * Gets the value of the kontaktPodaci property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getKontaktPodaci() {
            return kontaktPodaci;
        }

        /**
         * Sets the value of the kontaktPodaci property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setKontaktPodaci(String value) {
            this.kontaktPodaci = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Adresa" type="{http://ftn.uns.ac.rs/tim5/apipoverenik/model/util}Adresa"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "adresa"
    })
    public static class Poverenik {

        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;

        /**
         * Gets the value of the adresa property.
         *
         * @return possible object is
         * {@link Adresa }
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         *
         * @param value allowed object is
         *              {@link Adresa }
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

    }

}
