//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:31:45 PM CET 
//


package model.zalbaCutanja;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="poverenik" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="zakon" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov"/&gt;
 *         &lt;element name="organ_vlasti" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="razlog" type="{http://ftn.uns.ac.rs/tim5/util}Razlog"/&gt;
 *         &lt;element name="datum_zahteva" type="{http://ftn.uns.ac.rs/tim5/util}Datum"/&gt;
 *         &lt;element name="zahtevana_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="podnosioc_zalbe" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datum_zalbe" type="{http://ftn.uns.ac.rs/tim5/util}Datum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poverenik",
    "zakon",
    "organVlasti",
    "razlog",
    "datumZahteva",
    "zahtevanaInformacije",
    "podnosiocZalbe",
    "mesto",
    "datumZalbe"
})
@XmlRootElement(name = "zalba_cutanja", namespace = "http://www.zalba_cutanja.com")
public class ZalbaCutanja {

    @XmlElement(namespace = "http://www.zalba_cutanja.com", required = true)
    protected Object poverenik;
    @XmlElement(namespace = "http://www.zalba_cutanja.com", required = true)
    protected TPravniOsnov zakon;
    @XmlElement(name = "organ_vlasti", namespace = "http://www.zalba_cutanja.com", required = true)
    protected String organVlasti;
    @XmlElement(namespace = "http://www.zalba_cutanja.com", required = true, defaultValue = "\u043d\u0438\u0458\u0435 \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043e")
    @XmlSchemaType(name = "string")
    protected Razlog razlog;
    @XmlElement(name = "datum_zahteva", namespace = "http://www.zalba_cutanja.com", required = true)
    protected Datum datumZahteva;
    @XmlElement(name = "zahtevana_informacije", namespace = "http://www.zalba_cutanja.com", required = true)
    protected String zahtevanaInformacije;
    @XmlElement(name = "podnosioc_zalbe", namespace = "http://www.zalba_cutanja.com", required = true)
    protected Object podnosiocZalbe;
    @XmlElement(namespace = "http://www.zalba_cutanja.com", required = true)
    protected String mesto;
    @XmlElement(name = "datum_zalbe", namespace = "http://www.zalba_cutanja.com", required = true)
    protected Datum datumZalbe;

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPoverenik(Object value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the zakon property.
     * 
     * @return
     *     possible object is
     *     {@link TPravniOsnov }
     *     
     */
    public TPravniOsnov getZakon() {
        return zakon;
    }

    /**
     * Sets the value of the zakon property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravniOsnov }
     *     
     */
    public void setZakon(TPravniOsnov value) {
        this.zakon = value;
    }

    /**
     * Gets the value of the organVlasti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganVlasti(String value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the razlog property.
     * 
     * @return
     *     possible object is
     *     {@link Razlog }
     *     
     */
    public Razlog getRazlog() {
        return razlog;
    }

    /**
     * Sets the value of the razlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Razlog }
     *     
     */
    public void setRazlog(Razlog value) {
        this.razlog = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatumZahteva(Datum value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the zahtevanaInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevanaInformacije() {
        return zahtevanaInformacije;
    }

    /**
     * Sets the value of the zahtevanaInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevanaInformacije(String value) {
        this.zahtevanaInformacije = value;
    }

    /**
     * Gets the value of the podnosiocZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPodnosiocZalbe() {
        return podnosiocZalbe;
    }

    /**
     * Sets the value of the podnosiocZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPodnosiocZalbe(Object value) {
        this.podnosiocZalbe = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datumZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatumZalbe() {
        return datumZalbe;
    }

    /**
     * Sets the value of the datumZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatumZalbe(Datum value) {
        this.datumZalbe = value;
    }

}
