//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 12:15:06 PM CET 
//


package rs.ac.uns.ftn.tim5.apipoverenik.model.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Razlog.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Razlog">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="nije postupio"/>
 *     &lt;enumeration value="nije postupio u celosti"/>
 *     &lt;enumeration value="u zakonskom roku"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Razlog")
@XmlEnum
public enum Razlog {

    @XmlEnumValue("nije postupio")
    NIJE_POSTUPIO("nije postupio"),
    @XmlEnumValue("nije postupio u celosti")
    NIJE_POSTUPIO_U_CELOSTI("nije postupio u celosti"),
    @XmlEnumValue("u zakonskom roku")
    U_ZAKONSKOM_ROKU("u zakonskom roku");
    private final String value;

    Razlog(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Razlog fromValue(String v) {
        for (Razlog c: Razlog.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
