//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 08:04:17 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.resenje;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TPravniOsnov;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tekst_konteksta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Pravni_osnov" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravni_Osnov"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Zalba">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum_podnosenja_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *                   &lt;element name="Tip_zalbe" type="{http://ftn.uns.ac.rs/tim5/model/resenje}TTip_zalbe"/>
 *                   &lt;element name="Podnosilac" type="{http://ftn.uns.ac.rs/tim5/model/resenje}TOsoba"/>
 *                   &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tekstKonteksta",
    "zalba"
})
@XmlRootElement(name = "Kontekst")
public class Kontekst {

    @XmlElement(name = "Tekst_konteksta", required = true)
    protected Kontekst.TekstKonteksta tekstKonteksta;
    @XmlElement(name = "Zalba", required = true)
    protected Kontekst.Zalba zalba;

    /**
     * Gets the value of the tekstKonteksta property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst.TekstKonteksta }
     *     
     */
    public Kontekst.TekstKonteksta getTekstKonteksta() {
        return tekstKonteksta;
    }

    /**
     * Sets the value of the tekstKonteksta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst.TekstKonteksta }
     *     
     */
    public void setTekstKonteksta(Kontekst.TekstKonteksta value) {
        this.tekstKonteksta = value;
    }

    /**
     * Gets the value of the zalba property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst.Zalba }
     *     
     */
    public Kontekst.Zalba getZalba() {
        return zalba;
    }

    /**
     * Sets the value of the zalba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst.Zalba }
     *     
     */
    public void setZalba(Kontekst.Zalba value) {
        this.zalba = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Pravni_osnov" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravni_Osnov"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class TekstKonteksta {

        @XmlElementRef(name = "Pravni_osnov", namespace = "http://ftn.uns.ac.rs/tim5/model/resenje", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link TPravniOsnov }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum_podnosenja_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
     *         &lt;element name="Tip_zalbe" type="{http://ftn.uns.ac.rs/tim5/model/resenje}TTip_zalbe"/>
     *         &lt;element name="Podnosilac" type="{http://ftn.uns.ac.rs/tim5/model/resenje}TOsoba"/>
     *         &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datumPodnosenjaZahteva",
        "tipZalbe",
        "podnosilac",
        "organVlasti"
    })
    public static class Zalba {

        @XmlElement(name = "Datum_podnosenja_zahteva", required = true)
        protected Datum datumPodnosenjaZahteva;
        @XmlElement(name = "Tip_zalbe", required = true)
        protected TTipZalbe tipZalbe;
        @XmlElement(name = "Podnosilac", required = true)
        protected TOsoba podnosilac;
        @XmlElement(name = "Organ_vlasti", required = true)
        protected TPravnoLice organVlasti;

        /**
         * Gets the value of the datumPodnosenjaZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link Datum }
         *     
         */
        public Datum getDatumPodnosenjaZahteva() {
            return datumPodnosenjaZahteva;
        }

        /**
         * Sets the value of the datumPodnosenjaZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link Datum }
         *     
         */
        public void setDatumPodnosenjaZahteva(Datum value) {
            this.datumPodnosenjaZahteva = value;
        }

        /**
         * Gets the value of the tipZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link TTipZalbe }
         *     
         */
        public TTipZalbe getTipZalbe() {
            return tipZalbe;
        }

        /**
         * Sets the value of the tipZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link TTipZalbe }
         *     
         */
        public void setTipZalbe(TTipZalbe value) {
            this.tipZalbe = value;
        }

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link TOsoba }
         *     
         */
        public TOsoba getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TOsoba }
         *     
         */
        public void setPodnosilac(TOsoba value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the organVlasti property.
         * 
         * @return
         *     possible object is
         *     {@link TPravnoLice }
         *     
         */
        public TPravnoLice getOrganVlasti() {
            return organVlasti;
        }

        /**
         * Sets the value of the organVlasti property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPravnoLice }
         *     
         */
        public void setOrganVlasti(TPravnoLice value) {
            this.organVlasti = value;
        }

    }

}
