//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.27 at 11:01:10 AM CEST 
//


package rs.ac.uns.ftn.tim5.model.resenje;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TFizickoLice;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datum_resenja">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum_resenja" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="broj_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zalba">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum_podnosenja_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *                   &lt;element name="Tip_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Podnosilac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="odluka">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prihvaceno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="odbijena_zalba" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="odbijen_zahtev" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:odluka_poverenika" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poverenik">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:poverenik" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_zalbe" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_poverenika" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://ftn.uns.ac.rs.tim5/model/predicate" />
 *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:zalba_url" />
 *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tip_zalbe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resenje", propOrder = {
    "datumResenja",
    "brojResenja",
    "zalba",
    "odluka",
    "obrazlozenje",
    "poverenik"
})
@XmlRootElement(name = "Resenje")
public class Resenje implements Identifiable {

    @XmlElement(name = "datum_resenja", required = true)
    protected DatumResenja datumResenja;
    @XmlElement(name = "broj_resenja", required = true)
    protected String brojResenja;
    @XmlElement(required = true)
    protected Zalba zalba;
    @XmlElement(required = true)
    protected Odluka odluka;
    @XmlElement(required = true)
    protected String obrazlozenje;
    @XmlElement(required = true)
    protected Poverenik poverenik;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "id_zalbe")
    protected Long idZalbe;
    @XmlAttribute(name = "id_poverenika")
    protected Long idPoverenika;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anyURI")
    protected String about;
    @XmlAttribute(name = "vocab")
    protected String vocab;
    @XmlAttribute(name = "property")
    protected String property;
    @XmlAttribute(name = "content")
    protected String content;
    @XmlAttribute(name = "tip_zalbe")
    protected String tipZalbe;

    /**
     * Gets the value of the datumResenja property.
     *
     * @return
     *     possible object is
     *     {@link DatumResenja }
     *
     */
    public DatumResenja getDatumResenja() {
        return datumResenja;
    }

    /**
     * Sets the value of the datumResenja property.
     *
     * @param value
     *     allowed object is
     *     {@link DatumResenja }
     *
     */
    public void setDatumResenja(DatumResenja value) {
        this.datumResenja = value;
    }

    /**
     * Gets the value of the brojResenja property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBrojResenja() {
        return brojResenja;
    }

    /**
     * Sets the value of the brojResenja property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBrojResenja(String value) {
        this.brojResenja = value;
    }

    /**
     * Gets the value of the zalba property.
     *
     * @return
     *     possible object is
     *     {@link Zalba }
     *
     */
    public Zalba getZalba() {
        return zalba;
    }

    /**
     * Sets the value of the zalba property.
     *
     * @param value
     *     allowed object is
     *     {@link Zalba }
     *
     */
    public void setZalba(Zalba value) {
        this.zalba = value;
    }

    /**
     * Gets the value of the odluka property.
     *
     * @return
     *     possible object is
     *     {@link Odluka }
     *
     */
    public Odluka getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     *
     * @param value
     *     allowed object is
     *     {@link Odluka }
     *
     */
    public void setOdluka(Odluka value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the poverenik property.
     *
     * @return
     *     possible object is
     *     {@link Poverenik }
     *
     */
    public Poverenik getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     *
     * @param value
     *     allowed object is
     *     {@link Poverenik }
     *
     */
    public void setPoverenik(Poverenik value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdZalbe() {
        return idZalbe;
    }

    /**
     * Sets the value of the idZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdZalbe(Long value) {
        this.idZalbe = value;
    }

    /**
     * Gets the value of the idPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdPoverenika() {
        return idPoverenika;
    }

    /**
     * Sets the value of the idPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdPoverenika(Long value) {
        this.idPoverenika = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        if (vocab == null) {
            return "http://ftn.uns.ac.rs.tim5/model/predicate";
        } else {
            return vocab;
        }
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperty() {
        if (property == null) {
            return "pred:zalba_url";
        } else {
            return property;
        }
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperty(String value) {
        this.property = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the tipZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipZalbe() {
        return tipZalbe;
    }

    /**
     * Sets the value of the tipZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipZalbe(String value) {
        this.tipZalbe = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum_resenja" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DatumResenja
        extends Datum
    {

        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:datum_resenja";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prihvaceno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="odbijena_zalba" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="odbijen_zahtev" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:odluka_poverenika" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prihvaceno",
        "odbijenaZalba",
        "odbijenZahtev"
    })
    public static class Odluka {

        protected boolean prihvaceno;
        @XmlElement(name = "odbijena_zalba")
        protected boolean odbijenaZalba;
        @XmlElement(name = "odbijen_zahtev")
        protected boolean odbijenZahtev;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the prihvaceno property.
         * 
         */
        public boolean isPrihvaceno() {
            return prihvaceno;
        }

        /**
         * Sets the value of the prihvaceno property.
         * 
         */
        public void setPrihvaceno(boolean value) {
            this.prihvaceno = value;
        }

        /**
         * Gets the value of the odbijenaZalba property.
         * 
         */
        public boolean isOdbijenaZalba() {
            return odbijenaZalba;
        }

        /**
         * Sets the value of the odbijenaZalba property.
         * 
         */
        public void setOdbijenaZalba(boolean value) {
            this.odbijenaZalba = value;
        }

        /**
         * Gets the value of the odbijenZahtev property.
         * 
         */
        public boolean isOdbijenZahtev() {
            return odbijenZahtev;
        }

        /**
         * Sets the value of the odbijenZahtev property.
         * 
         */
        public void setOdbijenZahtev(boolean value) {
            this.odbijenZahtev = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:odluka_poverenika";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:poverenik" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Poverenik
        extends TFizickoLice
    {

        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:poverenik";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum_podnosenja_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
     *         &lt;element name="Tip_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Podnosilac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datumPodnosenjaZahteva",
        "tipZalbe",
        "podnosilac",
        "organVlasti"
    })
    public static class Zalba {

        @XmlElement(name = "Datum_podnosenja_zahteva", required = true)
        protected Datum datumPodnosenjaZahteva;
        @XmlElement(name = "Tip_zalbe", required = true)
        protected String tipZalbe;
        @XmlElement(name = "Podnosilac", required = true)
        protected String podnosilac;
        @XmlElement(name = "Organ_vlasti", required = true)
        protected TPravnoLice organVlasti;

        /**
         * Gets the value of the datumPodnosenjaZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link Datum }
         *     
         */
        public Datum getDatumPodnosenjaZahteva() {
            return datumPodnosenjaZahteva;
        }

        /**
         * Sets the value of the datumPodnosenjaZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link Datum }
         *     
         */
        public void setDatumPodnosenjaZahteva(Datum value) {
            this.datumPodnosenjaZahteva = value;
        }

        /**
         * Gets the value of the tipZalbe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipZalbe() {
            return tipZalbe;
        }

        /**
         * Sets the value of the tipZalbe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipZalbe(String value) {
            this.tipZalbe = value;
        }

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosilac(String value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the organVlasti property.
         * 
         * @return
         *     possible object is
         *     {@link TPravnoLice }
         *     
         */
        public TPravnoLice getOrganVlasti() {
            return organVlasti;
        }

        /**
         * Sets the value of the organVlasti property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPravnoLice }
         *     
         */
        public void setOrganVlasti(TPravnoLice value) {
            this.organVlasti = value;
        }

    }

}
