//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:23:46 PM CET 
//


package ftn.xmlws.tim5.apiorganvlasti.model.zahtev;

import java.util.ArrayList;
import java.util.List;

import ftn.xmlws.tim5.apiorganvlasti.model.util.*;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Trazilac" type="{http://ftn.uns.ac.rs/tim5/util}TFizicko_Lice"/&gt;
 *         &lt;element name="Organ" type="{http://ftn.uns.ac.rs/tim5/util}TPravno_Lice"/&gt;
 *         &lt;element name="Pravni_Osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Opis_Zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Elementi_Zahteva"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Element_Zahteva" type="{http://ftn.uns.ac.rs/tim5/util}TElement_Zahteva" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Datum" type="{http://ftn.uns.ac.rs/tim5/util}Datum"/&gt;
 *         &lt;element name="Mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trazilac",
    "organ",
    "pravniOsnov",
    "opisZahteva",
    "elementiZahteva",
    "datum",
    "mesto"
})
@XmlRootElement(name = "Zahtev", namespace = "http://ftn.uns.ac.rs/tim5/zahtev")
public class Zahtev {

    @XmlElement(name = "Trazilac", namespace = "http://ftn.uns.ac.rs/tim5/util", required = true)
    protected TFizickoLice trazilac;
    @XmlElement(name = "Organ", namespace = "http://ftn.uns.ac.rs/tim5/util", required = true)
    protected TPravnoLice organ;
    @XmlElement(name = "Pravni_Osnov", namespace = "http://ftn.uns.ac.rs/tim5/util")
    protected List<TPravniOsnov> pravniOsnov;
    @XmlElement(name = "Opis_Zahteva", namespace = "http://ftn.uns.ac.rs/tim5/zahtev", required = true)
    protected String opisZahteva;
    @XmlElement(name = "Elementi_Zahteva", namespace = "http://ftn.uns.ac.rs/tim5/zahtev", required = true)
    protected Zahtev.ElementiZahteva elementiZahteva;
    @XmlElement(name = "Datum", namespace = "http://ftn.uns.ac.rs/tim5/util", required = true)
    protected Datum datum;
    @XmlElement(name = "Mesto", namespace = "http://ftn.uns.ac.rs/tim5/zahtev", required = true)
    protected String mesto;

    /**
     * Gets the value of the trazilac property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getTrazilac() {
        return trazilac;
    }

    /**
     * Sets the value of the trazilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setTrazilac(TFizickoLice value) {
        this.trazilac = value;
    }

    /**
     * Gets the value of the organ property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setOrgan(TPravnoLice value) {
        this.organ = value;
    }

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the pravniOsnov property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPravniOsnov().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPravniOsnov }
     * 
     * 
     */
    public List<TPravniOsnov> getPravniOsnov() {
        if (pravniOsnov == null) {
            pravniOsnov = new ArrayList<TPravniOsnov>();
        }
        return this.pravniOsnov;
    }

    /**
     * Gets the value of the opisZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisZahteva() {
        return opisZahteva;
    }

    /**
     * Sets the value of the opisZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisZahteva(String value) {
        this.opisZahteva = value;
    }

    /**
     * Gets the value of the elementiZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link Zahtev.ElementiZahteva }
     *     
     */
    public Zahtev.ElementiZahteva getElementiZahteva() {
        return elementiZahteva;
    }

    /**
     * Sets the value of the elementiZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zahtev.ElementiZahteva }
     *     
     */
    public void setElementiZahteva(Zahtev.ElementiZahteva value) {
        this.elementiZahteva = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatum(Datum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Element_Zahteva" type="{http://ftn.uns.ac.rs/tim5/util}TElement_Zahteva" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementZahteva"
    })
    public static class ElementiZahteva {

        @XmlElement(name = "Element_Zahteva", namespace = "http://ftn.uns.ac.rs/tim5/util", required = true)
        protected List<TElementZahteva> elementZahteva;

        /**
         * Gets the value of the elementZahteva property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the elementZahteva property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementZahteva().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TElementZahteva }
         * 
         * 
         */
        public List<TElementZahteva> getElementZahteva() {
            if (elementZahteva == null) {
                elementZahteva = new ArrayList<TElementZahteva>();
            }
            return this.elementZahteva;
        }

    }

}
