//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 08:04:17 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Obavestenje.Predmet }
     * 
     */
    public Obavestenje.Predmet createObavestenjePredmet() {
        return new Obavestenje.Predmet();
    }

    /**
     * Create an instance of {@link Obavestenje.Odbijen }
     * 
     */
    public Obavestenje.Odbijen createObavestenjeOdbijen() {
        return new Obavestenje.Odbijen();
    }

    /**
     * Create an instance of {@link Obavestenje.Istekao }
     * 
     */
    public Obavestenje.Istekao createObavestenjeIstekao() {
        return new Obavestenje.Istekao();
    }

    /**
     * Create an instance of {@link Obavestenje.Trazilac }
     * 
     */
    public Obavestenje.Trazilac createObavestenjeTrazilac() {
        return new Obavestenje.Trazilac();
    }

    /**
     * Create an instance of {@link Obavestenje.Organ }
     * 
     */
    public Obavestenje.Organ createObavestenjeOrgan() {
        return new Obavestenje.Organ();
    }

    /**
     * Create an instance of {@link KolekcijaObavestenja }
     * 
     */
    public KolekcijaObavestenja createKolekcijaObavestenja() {
        return new KolekcijaObavestenja();
    }

    /**
     * Create an instance of {@link Obavestenje.Predmet.Datum }
     * 
     */
    public Obavestenje.Predmet.Datum createObavestenjePredmetDatum() {
        return new Obavestenje.Predmet.Datum();
    }

}
