//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 12:46:09 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.zalba_na_odluku;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Adresa;
import rs.ac.uns.ftn.tim5.model.util.Datum;
import rs.ac.uns.ftn.tim5.model.util.TFizickoLice;
import rs.ac.uns.ftn.tim5.model.util.TPravnoLice;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poverenik" type="{http://ftn.uns.ac.rs/tim5/model/util}Adresa"/>
 *         &lt;element name="zalilac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="osnovni_podaci" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
 *                   &lt;element name="drugi_podaci_za_kontakt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:email_trazioca" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="organ_vlasti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:naziv_organa_vlasti" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datum_zahteva" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *         &lt;element name="odluka">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broj_odluke">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="godina">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="osnova_za_zaljenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mesto_zalbe">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datum_zalbe">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="odgovor_organa_vlasti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prihvatio">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:prihvatio" />
 *                           &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="odbio">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:odbio" />
 *                           &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://ftn.uns.ac.rs.tim5/model/predicate" />
 *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:obavestenje_url" />
 *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_zahteva" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_obavestenja" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poverenik",
    "zalilac",
    "organVlasti",
    "datumZahteva",
    "odluka",
    "osnovaZaZaljenje",
    "mestoZalbe",
    "datumZalbe",
    "odgovorOrganaVlasti"
})
@XmlRootElement(name = "Zalba_na_odluku")
public class ZalbaNaOdluku implements Identifiable {

    @XmlElement(required = true)
    protected Adresa poverenik;
    @XmlElement(required = true)
    protected Zalilac zalilac;
    @XmlElement(name = "organ_vlasti", required = true)
    protected OrganVlasti organVlasti;
    @XmlElement(name = "datum_zahteva", required = true)
    protected Datum datumZahteva;
    @XmlElement(required = true)
    protected Odluka odluka;
    @XmlElement(name = "osnova_za_zaljenje", required = true)
    protected String osnovaZaZaljenje;
    @XmlElement(name = "mesto_zalbe", required = true)
    protected MestoZalbe mestoZalbe;
    @XmlElement(name = "datum_zalbe", required = true)
    protected DatumZalbe datumZalbe;
    @XmlElement(name = "odgovor_organa_vlasti", required = true)
    protected OdgovorOrganaVlasti odgovorOrganaVlasti;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anyURI")
    protected String about;
    @XmlAttribute(name = "vocab")
    protected String vocab;
    @XmlAttribute(name = "property")
    protected String property;
    @XmlAttribute(name = "content")
    protected String content;
    @XmlAttribute(name = "id_zahteva")
    protected Long idZahteva;
    @XmlAttribute(name = "id_obavestenja")
    protected Long idObavestenja;

    /**
     * Gets the value of the poverenik property.
     *
     * @return
     *     possible object is
     *     {@link Adresa }
     *
     */
    public Adresa getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     *
     * @param value
     *     allowed object is
     *     {@link Adresa }
     *
     */
    public void setPoverenik(Adresa value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the zalilac property.
     *
     * @return
     *     possible object is
     *     {@link Zalilac }
     *
     */
    public Zalilac getZalilac() {
        return zalilac;
    }

    /**
     * Sets the value of the zalilac property.
     *
     * @param value
     *     allowed object is
     *     {@link Zalilac }
     *
     */
    public void setZalilac(Zalilac value) {
        this.zalilac = value;
    }

    /**
     * Gets the value of the organVlasti property.
     *
     * @return
     *     possible object is
     *     {@link OrganVlasti }
     *
     */
    public OrganVlasti getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganVlasti }
     *
     */
    public void setOrganVlasti(OrganVlasti value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     *
     * @return
     *     possible object is
     *     {@link Datum }
     *
     */
    public Datum getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     *
     * @param value
     *     allowed object is
     *     {@link Datum }
     *
     */
    public void setDatumZahteva(Datum value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the odluka property.
     *
     * @return
     *     possible object is
     *     {@link Odluka }
     *
     */
    public Odluka getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     *
     * @param value
     *     allowed object is
     *     {@link Odluka }
     *
     */
    public void setOdluka(Odluka value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the osnovaZaZaljenje property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOsnovaZaZaljenje() {
        return osnovaZaZaljenje;
    }

    /**
     * Sets the value of the osnovaZaZaljenje property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOsnovaZaZaljenje(String value) {
        this.osnovaZaZaljenje = value;
    }

    /**
     * Gets the value of the mestoZalbe property.
     *
     * @return
     *     possible object is
     *     {@link MestoZalbe }
     *
     */
    public MestoZalbe getMestoZalbe() {
        return mestoZalbe;
    }

    /**
     * Sets the value of the mestoZalbe property.
     *
     * @param value
     *     allowed object is
     *     {@link MestoZalbe }
     *
     */
    public void setMestoZalbe(MestoZalbe value) {
        this.mestoZalbe = value;
    }

    /**
     * Gets the value of the datumZalbe property.
     *
     * @return
     *     possible object is
     *     {@link DatumZalbe }
     *
     */
    public DatumZalbe getDatumZalbe() {
        return datumZalbe;
    }

    /**
     * Sets the value of the datumZalbe property.
     *
     * @param value
     *     allowed object is
     *     {@link DatumZalbe }
     *
     */
    public void setDatumZalbe(DatumZalbe value) {
        this.datumZalbe = value;
    }

    /**
     * Gets the value of the odgovorOrganaVlasti property.
     *
     * @return
     *     possible object is
     *     {@link OdgovorOrganaVlasti }
     *
     */
    public OdgovorOrganaVlasti getOdgovorOrganaVlasti() {
        return odgovorOrganaVlasti;
    }

    /**
     * Sets the value of the odgovorOrganaVlasti property.
     *
     * @param value
     *     allowed object is
     *     {@link OdgovorOrganaVlasti }
     *
     */
    public void setOdgovorOrganaVlasti(OdgovorOrganaVlasti value) {
        this.odgovorOrganaVlasti = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the vocab property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVocab() {
        if (vocab == null) {
            return "http://ftn.uns.ac.rs.tim5/model/predicate";
        } else {
            return vocab;
        }
    }

    /**
     * Sets the value of the vocab property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVocab(String value) {
        this.vocab = value;
    }

    /**
     * Gets the value of the property property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProperty() {
        if (property == null) {
            return "pred:obavestenje_url";
        } else {
            return property;
        }
    }

    /**
     * Sets the value of the property property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProperty(String value) {
        this.property = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the idZahteva property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getIdZahteva() {
        return idZahteva;
    }

    /**
     * Sets the value of the idZahteva property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setIdZahteva(Long value) {
        this.idZahteva = value;
    }

    /**
     * Gets the value of the idObavestenja property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getIdObavestenja() {
        return idObavestenja;
    }

    /**
     * Sets the value of the idObavestenja property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setIdObavestenja(Long value) {
        this.idObavestenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}Datum">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:datum" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DatumZalbe
        extends Datum
    {

        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the property property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getProperty() {
            if (property == null) {
                return "pred:datum";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:mesto" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MestoZalbe {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getProperty() {
            if (property == null) {
                return "pred:mesto";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prihvatio">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:prihvatio" />
     *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="odbio">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:odbio" />
     *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prihvatio",
        "odbio"
    })
    public static class OdgovorOrganaVlasti {

        @XmlElement(required = true, defaultValue = "ne")
        protected Prihvatio prihvatio;
        @XmlElement(required = true, defaultValue = "ne")
        protected Odbio odbio;

        /**
         * Gets the value of the prihvatio property.
         *
         * @return
         *     possible object is
         *     {@link Prihvatio }
         *
         */
        public Prihvatio getPrihvatio() {
            return prihvatio;
        }

        /**
         * Sets the value of the prihvatio property.
         *
         * @param value
         *     allowed object is
         *     {@link Prihvatio }
         *
         */
        public void setPrihvatio(Prihvatio value) {
            this.prihvatio = value;
        }

        /**
         * Gets the value of the odbio property.
         *
         * @return
         *     possible object is
         *     {@link Odbio }
         *
         */
        public Odbio getOdbio() {
            return odbio;
        }

        /**
         * Sets the value of the odbio property.
         *
         * @param value
         *     allowed object is
         *     {@link Odbio }
         *
         */
        public void setOdbio(Odbio value) {
            this.odbio = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:odbio" />
         *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Odbio {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;
            @XmlAttribute(name = "content")
            protected String content;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:odbio";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:prihvatio" />
         *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Prihvatio {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;
            @XmlAttribute(name = "content")
            protected String content;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:prihvatio";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broj_odluke">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="godina">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}gYear">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojOdluke",
        "godina"
    })
    public static class Odluka {

        @XmlElement(name = "broj_odluke", required = true, defaultValue = "1")
        protected BigInteger brojOdluke;
        @XmlElement(required = true, defaultValue = "2020")
        protected XMLGregorianCalendar godina;

        /**
         * Gets the value of the brojOdluke property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrojOdluke() {
            return brojOdluke;
        }

        /**
         * Sets the value of the brojOdluke property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrojOdluke(BigInteger value) {
            this.brojOdluke = value;
        }

        /**
         * Gets the value of the godina property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getGodina() {
            return godina;
        }

        /**
         * Sets the value of the godina property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setGodina(XMLGregorianCalendar value) {
            this.godina = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ftn.uns.ac.rs/tim5/model/util}TPravno_Lice">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:naziv_organa_vlasti" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrganVlasti
        extends TPravnoLice
    {

        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:naziv_organa_vlasti";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="osnovni_podaci" type="{http://ftn.uns.ac.rs/tim5/model/util}TFizicko_Lice"/>
     *         &lt;element name="drugi_podaci_za_kontakt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" default="pred:email_trazioca" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovniPodaci",
        "drugiPodaciZaKontakt"
    })
    public static class Zalilac {

        @XmlElement(name = "osnovni_podaci", required = true)
        protected TFizickoLice osnovniPodaci;
        @XmlElement(name = "drugi_podaci_za_kontakt")
        protected String drugiPodaciZaKontakt;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the osnovniPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getOsnovniPodaci() {
            return osnovniPodaci;
        }

        /**
         * Sets the value of the osnovniPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setOsnovniPodaci(TFizickoLice value) {
            this.osnovniPodaci = value;
        }

        /**
         * Gets the value of the drugiPodaciZaKontakt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrugiPodaciZaKontakt() {
            return drugiPodaciZaKontakt;
        }

        /**
         * Sets the value of the drugiPodaciZaKontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrugiPodaciZaKontakt(String value) {
            this.drugiPodaciZaKontakt = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:email_trazioca";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }

}
