version: "3.7"
services:
  xml-db-poverenik:
    image: existdb/existdb:latest
    ports:
      - "8084:8080"
    networks:
      - api-poverenik-network
  rdf-db-poverenik:
    build:
      context: .
      dockerfile: .docker.fuseki/Dockerfile
    ports:
      - "8085:3030"
    environment:
      - ADMIN_PASSWORD=password
    networks:
      - api-poverenik-network
  poverenik:
    build:
      context: .
      dockerfile: .docker.java/Dockerfile
    ports:
      - "8083:8080"
    environment:
      XML_DB_HOST: xml-db-poverenik
      XML_DB_USER: admin
      XML_DB_PORT: 8080
      RDF_DB_HOST: rdf-db-poverenik
      RDF_DB_PORT: 3030
      RDF_DB_PASSWORD: password
      SPRING_PORT: 8080
    networks:
      - api-poverenik-network
      - api-organ-vlasti-network
networks:
  api-poverenik-network:
    name: api-poverenik-network
  api-organ-vlasti-network:
    external:
      name: api-organ-vlasti-network