//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.27 at 11:01:10 AM CEST 
//


package rs.ac.uns.ftn.tim5.model.resenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.resenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link Resenje.DatumResenja }
     * 
     */
    public Resenje.DatumResenja createResenjeDatumResenja() {
        return new Resenje.DatumResenja();
    }

    /**
     * Create an instance of {@link Resenje.Zalba }
     * 
     */
    public Resenje.Zalba createResenjeZalba() {
        return new Resenje.Zalba();
    }

    /**
     * Create an instance of {@link Resenje.Odluka }
     * 
     */
    public Resenje.Odluka createResenjeOdluka() {
        return new Resenje.Odluka();
    }

    /**
     * Create an instance of {@link Resenje.Poverenik }
     * 
     */
    public Resenje.Poverenik createResenjePoverenik() {
        return new Resenje.Poverenik();
    }

    /**
     * Create an instance of {@link KolekcijaResenja }
     * 
     */
    public KolekcijaResenja createKolekcijaResenja() {
        return new KolekcijaResenja();
    }

}
