//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.04 at 07:43:17 PM CET 
//


package rs.ac.uns.ftn.tim5.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import rs.ac.uns.ftn.tim5.interfaces.Identifiable;
import rs.ac.uns.ftn.tim5.model.util.Datum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datum_resenja" type="{http://ftn.uns.ac.rs/tim5/model/util}Datum"/>
 *         &lt;element name="broj_resenja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/model/resenje}Kontekst"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/model/resenje}Odluka"/>
 *         &lt;element name="Poverenik" type="{http://ftn.uns.ac.rs/tim5/model/resenje}TOsoba"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_zalbe" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="id_poverenika" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumResenja",
    "brojResenja",
    "kontekst",
    "odluka",
    "poverenik"
})
@XmlRootElement(name = "Resenje")
public class Resenje implements Identifiable {

    @XmlElement(name = "datum_resenja", required = true)
    protected Datum datumResenja;
    @XmlElement(name = "broj_resenja", required = true)
    protected Object brojResenja;
    @XmlElement(name = "Kontekst", required = true)
    protected Kontekst kontekst;
    @XmlElement(name = "Odluka", required = true)
    protected Odluka odluka;
    @XmlElement(name = "Poverenik", required = true)
    protected TOsoba poverenik;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "id_zalbe")
    protected Long idZalbe;
    @XmlAttribute(name = "id_poverenika")
    protected Long idPoverenika;

    /**
     * Gets the value of the datumResenja property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatumResenja() {
        return datumResenja;
    }

    /**
     * Sets the value of the datumResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatumResenja(Datum value) {
        this.datumResenja = value;
    }

    /**
     * Gets the value of the brojResenja property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBrojResenja() {
        return brojResenja;
    }

    /**
     * Sets the value of the brojResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBrojResenja(Object value) {
        this.brojResenja = value;
    }

    /**
     * Gets the value of the kontekst property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst }
     *     
     */
    public Kontekst getKontekst() {
        return kontekst;
    }

    /**
     * Sets the value of the kontekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst }
     *     
     */
    public void setKontekst(Kontekst value) {
        this.kontekst = value;
    }

    /**
     * Gets the value of the odluka property.
     * 
     * @return
     *     possible object is
     *     {@link Odluka }
     *     
     */
    public Odluka getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odluka }
     *     
     */
    public void setOdluka(Odluka value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPoverenik(TOsoba value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdZalbe() {
        return idZalbe;
    }

    /**
     * Sets the value of the idZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdZalbe(Long value) {
        this.idZalbe = value;
    }

    /**
     * Gets the value of the idPoverenika property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdPoverenika() {
        return idPoverenika;
    }

    /**
     * Sets the value of the idPoverenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdPoverenika(Long value) {
        this.idPoverenika = value;
    }

}
