//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 03:28:30 PM CEST 
//


package rs.ac.uns.ftn.tim5.model.resenje;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTip_zalbe.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTip_zalbe">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="odbacivanje"/>
 *     &lt;enumeration value="nepostupanje"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTip_zalbe")
@XmlEnum
public enum TTipZalbe {

    @XmlEnumValue("odbacivanje")
    ODBACIVANJE("odbacivanje"),
    @XmlEnumValue("nepostupanje")
    NEPOSTUPANJE("nepostupanje");
    private final String value;

    TTipZalbe(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipZalbe fromValue(String v) {
        for (TTipZalbe c: TTipZalbe.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
