//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:22:08 PM CET 
//


package ftn.xmlws.tim5.apiorganvlasti.model.resenje;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import ftn.xmlws.tim5.apiorganvlasti.model.util.TPravnoLice;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tekst_konteksta"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="Pravni_osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Zalba"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Podnosilac" type="{http://ftn.uns.ac.rs/tim5/resenje}TOsoba"/&gt;
 *                   &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/util}TPravno_Lice"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="datum_podnosenja_zahteva" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                 &lt;attribute name="tip" type="{http://ftn.uns.ac.rs/tim5/resenje}TTip_zalbe" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tekstKonteksta",
    "zalba"
})
@XmlRootElement(name = "Kontekst", namespace = "http://ftn.uns.ac.rs/tim5/resenje")
public class Kontekst {

    @XmlElement(name = "Tekst_konteksta", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
    protected Kontekst.TekstKonteksta tekstKonteksta;
    @XmlElement(name = "Zalba", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
    protected Kontekst.Zalba zalba;

    /**
     * Gets the value of the tekstKonteksta property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst.TekstKonteksta }
     *     
     */
    public Kontekst.TekstKonteksta getTekstKonteksta() {
        return tekstKonteksta;
    }

    /**
     * Sets the value of the tekstKonteksta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst.TekstKonteksta }
     *     
     */
    public void setTekstKonteksta(Kontekst.TekstKonteksta value) {
        this.tekstKonteksta = value;
    }

    /**
     * Gets the value of the zalba property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst.Zalba }
     *     
     */
    public Kontekst.Zalba getZalba() {
        return zalba;
    }

    /**
     * Sets the value of the zalba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst.Zalba }
     *     
     */
    public void setZalba(Kontekst.Zalba value) {
        this.zalba = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="Pravni_osnov" type="{http://ftn.uns.ac.rs/tim5/util}TPravni_Osnov"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class TekstKonteksta {

        @XmlElementRef(name = "Pravni_osnov", namespace = "http://ftn.uns.ac.rs/tim5/resenje", type = JAXBElement.class, required = false)
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ftn.xmlws.tim5.apiorganvlasti.model.util.TPravniOsnov }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Podnosilac" type="{http://ftn.uns.ac.rs/tim5/resenje}TOsoba"/&gt;
     *         &lt;element name="Organ_vlasti" type="{http://ftn.uns.ac.rs/tim5/util}TPravno_Lice"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="datum_podnosenja_zahteva" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *       &lt;attribute name="tip" type="{http://ftn.uns.ac.rs/tim5/resenje}TTip_zalbe" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "organVlasti"
    })
    public static class Zalba {

        @XmlElement(name = "Podnosilac", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
        protected TOsoba podnosilac;
        @XmlElement(name = "Organ_vlasti", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
        protected TPravnoLice organVlasti;
        @XmlAttribute(name = "datum_podnosenja_zahteva")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPodnosenjaZahteva;
        @XmlAttribute(name = "tip")
        protected TTipZalbe tip;

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link TOsoba }
         *     
         */
        public TOsoba getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TOsoba }
         *     
         */
        public void setPodnosilac(TOsoba value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the organVlasti property.
         * 
         * @return
         *     possible object is
         *     {@link TPravnoLice }
         *     
         */
        public TPravnoLice getOrganVlasti() {
            return organVlasti;
        }

        /**
         * Sets the value of the organVlasti property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPravnoLice }
         *     
         */
        public void setOrganVlasti(TPravnoLice value) {
            this.organVlasti = value;
        }

        /**
         * Gets the value of the datumPodnosenjaZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenjaZahteva() {
            return datumPodnosenjaZahteva;
        }

        /**
         * Sets the value of the datumPodnosenjaZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenjaZahteva(XMLGregorianCalendar value) {
            this.datumPodnosenjaZahteva = value;
        }

        /**
         * Gets the value of the tip property.
         * 
         * @return
         *     possible object is
         *     {@link TTipZalbe }
         *     
         */
        public TTipZalbe getTip() {
            return tip;
        }

        /**
         * Sets the value of the tip property.
         * 
         * @param value
         *     allowed object is
         *     {@link TTipZalbe }
         *     
         */
        public void setTip(TTipZalbe value) {
            this.tip = value;
        }

    }

}
