//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:22:08 PM CET 
//


package ftn.xmlws.tim5.apiorganvlasti.model.resenje;

import javax.xml.namespace.QName;

import ftn.xmlws.tim5.apiorganvlasti.model.resenje.Kontekst;
import ftn.xmlws.tim5.apiorganvlasti.model.resenje.Odluka;
import ftn.xmlws.tim5.apiorganvlasti.model.resenje.Resenje;
import ftn.xmlws.tim5.apiorganvlasti.model.resenje.TOsoba;
import ftn.xmlws.tim5.apiorganvlasti.model.util.*;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.resenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OdlukaObrazlozenje_QNAME = new QName("http://ftn.uns.ac.rs/tim5/resenje", "Obrazlozenje");
    private final static QName _OdlukaObrazlozenjePravniOsnov_QNAME = new QName("http://ftn.uns.ac.rs/tim5/resenje", "Pravni_osnov");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kontekst }
     * 
     */
    public Kontekst createKontekst() {
        return new Kontekst();
    }

    /**
     * Create an instance of {@link Odluka }
     * 
     */
    public Odluka createOdluka() {
        return new Odluka();
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev }
     * 
     */
    public TOdgovorNaZahtev createTOdgovorNaZahtev() {
        return new TOdgovorNaZahtev();
    }

    /**
     * Create an instance of {@link TPravniOsnov }
     * 
     */
    public TPravniOsnov createTPravniOsnov() {
        return new TPravniOsnov();
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link Kontekst.TekstKonteksta }
     * 
     */
    public Kontekst.TekstKonteksta createKontekstTekstKonteksta() {
        return new Kontekst.TekstKonteksta();
    }

    /**
     * Create an instance of {@link Kontekst.Zalba }
     * 
     */
    public Kontekst.Zalba createKontekstZalba() {
        return new Kontekst.Zalba();
    }

    /**
     * Create an instance of {@link Odluka.Obrazlozenje }
     * 
     */
    public Odluka.Obrazlozenje createOdlukaObrazlozenje() {
        return new Odluka.Obrazlozenje();
    }

    /**
     * Create an instance of {@link TOsoba }
     * 
     */
    public TOsoba createTOsoba() {
        return new TOsoba();
    }

    /**
     * Create an instance of {@link Adresa }
     *
     *
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TLice }
     * 
     */
    public TLice createTLice() {
        return new TLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TDopunaPravnogOsnova }
     * 
     */
    public TDopunaPravnogOsnova createTDopunaPravnogOsnova() {
        return new TDopunaPravnogOsnova();
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link TElementZahteva }
     * 
     */
    public TElementZahteva createTElementZahteva() {
        return new TElementZahteva();
    }

    /**
     * Create an instance of {@link TVreme }
     * 
     */
    public TVreme createTVreme() {
        return new TVreme();
    }

    /**
     * Create an instance of {@link TUplata }
     * 
     */
    public TUplata createTUplata() {
        return new TUplata();
    }

    /**
     * Create an instance of {@link TRacun }
     * 
     */
    public TRacun createTRacun() {
        return new TRacun();
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev.Uvid }
     * 
     */
    public TOdgovorNaZahtev.Uvid createTOdgovorNaZahtevUvid() {
        return new TOdgovorNaZahtev.Uvid();
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev.Trosak }
     * 
     */
    public TOdgovorNaZahtev.Trosak createTOdgovorNaZahtevTrosak() {
        return new TOdgovorNaZahtev.Trosak();
    }

    /**
     * Create an instance of {@link TPravniOsnov.Dopune }
     * 
     */
    public TPravniOsnov.Dopune createTPravniOsnovDopune() {
        return new TPravniOsnov.Dopune();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Odluka.Obrazlozenje }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Odluka.Obrazlozenje }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/tim5/resenje", name = "Obrazlozenje", scope = Odluka.class)
    public JAXBElement<Odluka.Obrazlozenje> createOdlukaObrazlozenje(Odluka.Obrazlozenje value) {
        return new JAXBElement<Odluka.Obrazlozenje>(_OdlukaObrazlozenje_QNAME, Odluka.Obrazlozenje.class, Odluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravniOsnov }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TPravniOsnov }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/tim5/resenje", name = "Pravni_osnov", scope = Odluka.Obrazlozenje.class)
    public JAXBElement<TPravniOsnov> createOdlukaObrazlozenjePravniOsnov(TPravniOsnov value) {
        return new JAXBElement<TPravniOsnov>(_OdlukaObrazlozenjePravniOsnov_QNAME, TPravniOsnov.class, Odluka.Obrazlozenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPravniOsnov }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TPravniOsnov }{@code >}
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/tim5/resenje", name = "Pravni_osnov", scope = Kontekst.TekstKonteksta.class)
    public JAXBElement<TPravniOsnov> createKontekstTekstKontekstaPravniOsnov(TPravniOsnov value) {
        return new JAXBElement<TPravniOsnov>(_OdlukaObrazlozenjePravniOsnov_QNAME, TPravniOsnov.class, Kontekst.TekstKonteksta.class, value);
    }

}
