//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:22:08 PM CET 
//


package ftn.xmlws.tim5.apiorganvlasti.model.resenje;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/resenje}Kontekst"/&gt;
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/resenje}Odluka"/&gt;
 *         &lt;element name="Poverenik" type="{http://ftn.uns.ac.rs/tim5/resenje}TOsoba"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="broj_resenja" use="required" type="{http://ftn.uns.ac.rs/tim5/resenje}TBroj_resenja" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kontekst",
    "odluka",
    "poverenik"
})
@XmlRootElement(name = "Resenje", namespace = "http://ftn.uns.ac.rs/tim5/resenje")
public class Resenje {

    @XmlElement(name = "Kontekst", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
    protected Kontekst kontekst;
    @XmlElement(name = "Odluka", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
    protected Odluka odluka;
    @XmlElement(name = "Poverenik", namespace = "http://ftn.uns.ac.rs/tim5/resenje", required = true)
    protected TOsoba poverenik;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "broj_resenja", required = true)
    protected String brojResenja;

    /**
     * Gets the value of the kontekst property.
     * 
     * @return
     *     possible object is
     *     {@link Kontekst }
     *     
     */
    public Kontekst getKontekst() {
        return kontekst;
    }

    /**
     * Sets the value of the kontekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kontekst }
     *     
     */
    public void setKontekst(Kontekst value) {
        this.kontekst = value;
    }

    /**
     * Gets the value of the odluka property.
     * 
     * @return
     *     possible object is
     *     {@link Odluka }
     *     
     */
    public Odluka getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odluka }
     *     
     */
    public void setOdluka(Odluka value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPoverenik(TOsoba value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the brojResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojResenja() {
        return brojResenja;
    }

    /**
     * Sets the value of the brojResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojResenja(String value) {
        this.brojResenja = value;
    }

}
