//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 08:22:08 PM CET 
//


package ftn.xmlws.tim5.apiorganvlasti.model.resenje;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TIshod_odluke.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TIshod_odluke"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="osnovana_zalba"/&gt;
 *     &lt;enumeration value="neosnovana_zalba"/&gt;
 *     &lt;enumeration value="ponistena_zalba"/&gt;
 *     &lt;enumeration value="odbijen_zahtev"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TIshod_odluke", namespace = "http://ftn.uns.ac.rs/tim5/resenje")
@XmlEnum
public enum TIshodOdluke {

    @XmlEnumValue("osnovana_zalba")
    OSNOVANA_ZALBA("osnovana_zalba"),
    @XmlEnumValue("neosnovana_zalba")
    NEOSNOVANA_ZALBA("neosnovana_zalba"),
    @XmlEnumValue("ponistena_zalba")
    PONISTENA_ZALBA("ponistena_zalba"),
    @XmlEnumValue("odbijen_zahtev")
    ODBIJEN_ZAHTEV("odbijen_zahtev");
    private final String value;

    TIshodOdluke(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TIshodOdluke fromValue(String v) {
        for (TIshodOdluke c: TIshodOdluke.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
