//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.04 at 09:48:55 AM CET 
//


package rs.ac.uns.ftn.tim5.model.util;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev }
     * 
     */
    public TOdgovorNaZahtev createTOdgovorNaZahtev() {
        return new TOdgovorNaZahtev();
    }

    /**
     * Create an instance of {@link TPravniOsnov }
     * 
     */
    public TPravniOsnov createTPravniOsnov() {
        return new TPravniOsnov();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TLice }
     * 
     */
    public TLice createTLice() {
        return new TLice();
    }

    /**
     * Create an instance of {@link TRacun }
     * 
     */
    public TRacun createTRacun() {
        return new TRacun();
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TVreme }
     * 
     */
    public TVreme createTVreme() {
        return new TVreme();
    }

    /**
     * Create an instance of {@link TUplata }
     * 
     */
    public TUplata createTUplata() {
        return new TUplata();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TDopunaPravnogOsnova }
     * 
     */
    public TDopunaPravnogOsnova createTDopunaPravnogOsnova() {
        return new TDopunaPravnogOsnova();
    }

    /**
     * Create an instance of {@link TElementZahteva }
     * 
     */
    public TElementZahteva createTElementZahteva() {
        return new TElementZahteva();
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev.Uvid }
     * 
     */
    public TOdgovorNaZahtev.Uvid createTOdgovorNaZahtevUvid() {
        return new TOdgovorNaZahtev.Uvid();
    }

    /**
     * Create an instance of {@link TOdgovorNaZahtev.Trosak }
     * 
     */
    public TOdgovorNaZahtev.Trosak createTOdgovorNaZahtevTrosak() {
        return new TOdgovorNaZahtev.Trosak();
    }

    /**
     * Create an instance of {@link TPravniOsnov.Dopune }
     * 
     */
    public TPravniOsnov.Dopune createTPravniOsnovDopune() {
        return new TPravniOsnov.Dopune();
    }

}
