//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 09:23:40 PM CET 
//


package rs.ac.uns.ftn.tim5.apiorganvlasti.model.zahtev;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.apiorganvlasti.model.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllZahtevRequest_QNAME = new QName("http://ftn.uns.ac.rs/tim5/apiorganvlasti/model/zahtev", "getAllZahtevRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.apiorganvlasti.model.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link DeleteZahtevRequest }
     * 
     */
    public DeleteZahtevRequest createDeleteZahtevRequest() {
        return new DeleteZahtevRequest();
    }

    /**
     * Create an instance of {@link GetZahtevRequest }
     * 
     */
    public GetZahtevRequest createGetZahtevRequest() {
        return new GetZahtevRequest();
    }

    /**
     * Create an instance of {@link Zahtev.ElementiZahteva }
     * 
     */
    public Zahtev.ElementiZahteva createZahtevElementiZahteva() {
        return new Zahtev.ElementiZahteva();
    }

    /**
     * Create an instance of {@link GetZahtevResponse }
     * 
     */
    public GetZahtevResponse createGetZahtevResponse() {
        return new GetZahtevResponse();
    }

    /**
     * Create an instance of {@link CreateZahtevResponse }
     * 
     */
    public CreateZahtevResponse createCreateZahtevResponse() {
        return new CreateZahtevResponse();
    }

    /**
     * Create an instance of {@link DeleteZahtevResponse }
     * 
     */
    public DeleteZahtevResponse createDeleteZahtevResponse() {
        return new DeleteZahtevResponse();
    }

    /**
     * Create an instance of {@link UpdateZahtevResponse }
     * 
     */
    public UpdateZahtevResponse createUpdateZahtevResponse() {
        return new UpdateZahtevResponse();
    }

    /**
     * Create an instance of {@link GetAllZahtevResponse }
     * 
     */
    public GetAllZahtevResponse createGetAllZahtevResponse() {
        return new GetAllZahtevResponse();
    }

    /**
     * Create an instance of {@link CreateZahtevRequest }
     * 
     */
    public CreateZahtevRequest createCreateZahtevRequest() {
        return new CreateZahtevRequest();
    }

    /**
     * Create an instance of {@link UpdateZahtevRequest }
     * 
     */
    public UpdateZahtevRequest createUpdateZahtevRequest() {
        return new UpdateZahtevRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/tim5/apiorganvlasti/model/zahtev", name = "getAllZahtevRequest")
    public JAXBElement<Object> createGetAllZahtevRequest(Object value) {
        return new JAXBElement<Object>(_GetAllZahtevRequest_QNAME, Object.class, null, value);
    }

}
