//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 01:45:28 PM CET 
//


package rs.ac.uns.ftn.tim5.apipoverenik.model.zalbe_cutanja;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.apipoverenik.model.zalbe_cutanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.apipoverenik.model.zalbe_cutanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaCutanja }
     * 
     */
    public ZalbaCutanja createZalbaCutanja() {
        return new ZalbaCutanja();
    }

    /**
     * Create an instance of {@link KolekcijaZalbiCutanja }
     * 
     */
    public KolekcijaZalbiCutanja createKolekcijaZalbiCutanja() {
        return new KolekcijaZalbiCutanja();
    }

    /**
     * Create an instance of {@link ZalbaCutanja.Poverenik }
     * 
     */
    public ZalbaCutanja.Poverenik createZalbaCutanjaPoverenik() {
        return new ZalbaCutanja.Poverenik();
    }

    /**
     * Create an instance of {@link ZalbaCutanja.PodnosiocZalbe }
     * 
     */
    public ZalbaCutanja.PodnosiocZalbe createZalbaCutanjaPodnosiocZalbe() {
        return new ZalbaCutanja.PodnosiocZalbe();
    }

}
