//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 08:07:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://ftn.uns.ac.rs/tim5/model/izvestaj",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns={
                @XmlNs(prefix="xs", namespaceURI="http://www.w3.org/2001/XMLSchema#"),
                @XmlNs(prefix="pred", namespaceURI="http://ftn.uns.ac.rs/tim5/model/predicate/"),
                @XmlNs(prefix="util", namespaceURI = "http://ftn.uns.ac.rs/tim5/model/util"),
                @XmlNs(prefix="iz", namespaceURI = "http://ftn.uns.ac.rs/tim5/model/izvestaj")
        }
)
package rs.ac.uns.ftn.tim5.model.izvestaj;

import javax.xml.bind.annotation.XmlNs;
