//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 01:57:32 PM CET 
//


package rs.ac.uns.ftn.tim5.model.osnovnapretraga;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.tim5.model.osnovnapretraga package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.tim5.model.osnovnapretraga
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OsnovnaPretraga }
     * 
     */
    public OsnovnaPretraga createOsnovnaPretraga() {
        return new OsnovnaPretraga();
    }

    /**
     * Create an instance of {@link RezultatOsnovnePretrage }
     * 
     */
    public RezultatOsnovnePretrage createRezultatOsnovnePretrage() {
        return new RezultatOsnovnePretrage();
    }

}
