//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 01:57:32 PM CET 
//


package rs.ac.uns.ftn.tim5.model.osnovnapretraga;

import rs.ac.uns.ftn.tim5.model.izvestaj.KolekcijaIzvestaja;
import rs.ac.uns.ftn.tim5.model.resenje.KolekcijaResenja;
import rs.ac.uns.ftn.tim5.model.zahtev.KolekcijaZahteva;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/model/zahtev}Kolekcija_zahteva"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/model/resenje}Kolekcija_resenja"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/tim5/model/izvestaj}Kolekcija_Izvestaja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kolekcijaZahteva",
    "kolekcijaResenja",
    "kolekcijaIzvestaja"
})
@XmlRootElement(name = "Rezultat_Osnovne_Pretrage")
public class RezultatOsnovnePretrage {

    @XmlElement(name = "Kolekcija_zahteva", namespace = "http://ftn.uns.ac.rs/tim5/model/zahtev", required = true)
    protected KolekcijaZahteva kolekcijaZahteva;
    @XmlElement(name = "Kolekcija_resenja", namespace = "http://ftn.uns.ac.rs/tim5/model/resenje", required = true)
    protected KolekcijaResenja kolekcijaResenja;
    @XmlElement(name = "Kolekcija_Izvestaja", namespace = "http://ftn.uns.ac.rs/tim5/model/izvestaj", required = true)
    protected KolekcijaIzvestaja kolekcijaIzvestaja;

    /**
     * Gets the value of the kolekcijaZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link KolekcijaZahteva }
     *     
     */
    public KolekcijaZahteva getKolekcijaZahteva() {
        return kolekcijaZahteva;
    }

    /**
     * Sets the value of the kolekcijaZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link KolekcijaZahteva }
     *     
     */
    public void setKolekcijaZahteva(KolekcijaZahteva value) {
        this.kolekcijaZahteva = value;
    }

    /**
     * Gets the value of the kolekcijaResenja property.
     * 
     * @return
     *     possible object is
     *     {@link KolekcijaResenja }
     *     
     */
    public KolekcijaResenja getKolekcijaResenja() {
        return kolekcijaResenja;
    }

    /**
     * Sets the value of the kolekcijaResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link KolekcijaResenja }
     *     
     */
    public void setKolekcijaResenja(KolekcijaResenja value) {
        this.kolekcijaResenja = value;
    }

    /**
     * Gets the value of the kolekcijaIzvestaja property.
     * 
     * @return
     *     possible object is
     *     {@link KolekcijaIzvestaja }
     *     
     */
    public KolekcijaIzvestaja getKolekcijaIzvestaja() {
        return kolekcijaIzvestaja;
    }

    /**
     * Sets the value of the kolekcijaIzvestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link KolekcijaIzvestaja }
     *     
     */
    public void setKolekcijaIzvestaja(KolekcijaIzvestaja value) {
        this.kolekcijaIzvestaja = value;
    }

}
